# インサートモードに入ったら読み込む
[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = '''
    let g:neocomplete#enable_at_startup = 1
'''
on_i = 1

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

# [[plugins]]
# repo = 'Shougo/neosnippet'
# depends = ['neosnippet-snippets']
# on_i = 1
# on_ft = ['snippet']

#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'
